### ISSUE TITLE
Fix many `Initialization system is overdetermined` warning messages

### ISSUE THREAD

**Issue by orso82** [ProjectTorreyPines/ThermalSystemModels.jl#85]
@jacksonharvey, when you have time. We're seeing a lot of these warnings when running ThermalSystemModels.

https://github.com/ProjectTorreyPines/FUSE.jl/actions/runs/11864027768/job/33066645246#step:14:1071

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/7fc688c9-42b7-4dc9-a589-c5e87088da9d">

Would you be able to please take a look when you have time? Thanks!!

**Comment by jacksonharvey** [comment]
I'll check it out, not sure why that would be happening.
